# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8c272c45-eda1-4b00-bb2e-495caa77630d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8c272c45-eda1-4b00-bb2e-495caa77630d".device = "/dev/disk/by-uuid/8c272c45-eda1-4b00-bb2e-495caa77630d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DAF0-E1E3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-30aa08b2-a9b6-4c81-93b4-7b2f8def3f91"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
